In [5]:
import numpy
import scipy.special

In [6]:
# ニューラルネットワークの定義
class neuralNetwork:
    
    # 初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層、隠れ層、出力層のノード数の設定
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # リンクの重み行列 wih と who
        # 行列内の重み w_i_j, ノード i から次の層のノード j へのリンクの重み
        self.wih = numpy.random.normal(0.0,pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        print("self.wih",self.wih)
        self.who = numpy.random.normal(0.0,pow(self.onodes, -0.5), (self.onodes, self.hnodes))
        print("self.who",self.who)
        
        # 学習率の設定
        self.lr = learningrate
        
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass
    
    # 学習
    def train(self, inputs_list, targets_list):
            
            # 入力リストを行列に変換
            inputs = numpy.array(inputs_list, ndmin=2).T
            targets = numpy.array(targets_list, ndmin=2).T
            
            # 隠れ層に入ってくる信号の計算
            hidden_inputs = numpy.dots(self.wih, inputs)
            # 隠れ層で結合された信号を活性化関数により出力
            hidden_outputs = self.activation_function(hidden_inputs)
            
            # 出力層に入ってくる信号の計算
            final_inputs = numpy.dot(self.who, hidden_outputs)
            # 出力層で結合された信号を活性化関数により出力
            final_outputs = self.activation_function(final_inputs)
            
            # 出力の誤差 = (目標出力 - 最終出力)
            output_errors = targets - final_outputs
            
            # 隠れ層の誤差は出力層の誤差をリンクの重みの割合で分配
            hidden_errors = numpy.dot(self.who.T, output_errors)
            
            self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
            self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
            
            pass
        
    # 照会
    def query(self, inputs_list):
        # 入力リストを行列に変換
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        print("inputs",inputs)
        
        # 隠れ層に入ってくる信号の計算
        hidden_inputs = numpy.dot(self.wih, inputs)
        print("hidden_inputs",hidden_inputs)
        # 隠れ層で結合された信号を活性化関数により出力
        hidden_outputs = self.activation_function(hidden_inputs)
        print("hidden_outputs",hidden_outputs)
        
        # 出力層に入ってくる信号の計算
        final_inputs = numpy.dot(self.who, hidden_outputs)
        print("final_inputs",final_inputs)
        # 出力層で結合された信号を活性化関数により出力
        final_outputs = self.activation_function(final_inputs)
        print("final_outputs",final_outputs)
        
        return final_outputs


In [7]:
# 入力層、隠れ層、出力層のノード数
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# 学習率 = 0.3
learning_rate = 0.3

n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

self.wih [[-0.64456298 -0.2842766   0.27072414]
 [-1.02082632  0.14945707 -0.34756454]
 [-0.27874678 -0.62127468 -0.15618384]]
self.who [[ 0.55852041 -0.95084607 -0.04807819]
 [ 0.19950189  1.10565387 -0.24580982]
 [-0.15981915  0.28569616  0.56705179]]


In [8]:
n.query([1.0, 0.5, -1.5])

inputs [[ 1. ]
 [ 0.5]
 [-1.5]]
hidden_inputs [[-1.19278748]
 [-0.42475099]
 [-0.35510836]]
hidden_outputs [[ 0.23276077]
 [ 0.39538044]
 [ 0.41214421]]
final_inputs [[-0.26575945]
 [ 0.38228104]
 [ 0.30946616]]
final_outputs [[ 0.43394844]
 [ 0.59442314]
 [ 0.57675495]]


array([[ 0.43394844],
       [ 0.59442314],
       [ 0.57675495]])